### ISSUE TITLE
About challenge bug

### ISSUE THREAD

**Issue by zyjblockchain** [aoacc/arfleet-js#2]
https://github.com/aoacc/arfleet-js/blob/master/lua/ArFleetDeal.lua#L200
What I understand is that each time the provider gets a different challenge, but in this code, it says that it returns the same challenge, in which case the challenge is meaningless.
In this case, the challenge is meaningless. The provider will just store a merkle path of the challenge and delete the user's data.

**Comment by sergevar** [comment]
Hey @zyjblockchain thanks for looking at the code and participating in the discussion!

No, this function returns the current challenge, which is the same _within the current verification period_.

Note that if State.Challenge is not empty, it returns it and doesn't try to recreate
https://github.com/aoacc/arfleet-js/blob/master/lua/ArFleetDeal.lua#L223-L225

But, after the challenge is submitted, or failed and slashed, both of them call `AdvanceNextVerification`:

https://github.com/aoacc/arfleet-js/blob/master/lua/ArFleetDeal.lua#L53

Which sets `State.Challenge = ""`, and now `GetChallenge()` will have to create a random new one for the next verification period.

Let me know if that clarifies things

**Comment by zyjblockchain** [comment]
> Hey @zyjblockchain thanks for looking at the code and participating in the discussion!
> 
> No, this function returns the current challenge, which is the same _within the current verification period_.
> 
> Note that if State.Challenge is not empty, it returns it and doesn't try to recreate https://github.com/aoacc/arfleet-js/blob/master/lua/ArFleetDeal.lua#L223-L225
> 
> But, after the challenge is submitted, or failed and slashed, both of them call `AdvanceNextVerification`:
> 
> https://github.com/aoacc/arfleet-js/blob/master/lua/ArFleetDeal.lua#L53
> 
> Which sets `State.Challenge = ""`, and now `GetChallenge()` will have to create a random new one for the next verification period.
> 
> Let me know if that clarifies things

I see. Thank you.
